### ISSUE TITLE
register item qbcore

### ISSUE THREAD

**Issue by chiboto** [renzuzu/renzu_stancer#11]
How can i register the item? im assuming in qb-smallresources, item is installed in shared.lua, whenever i use it it just says no stancerkit installed

**Comment by prestigehairline** [comment]
I have the same problem..standalone version works like a charm,but qb version i cant seem to be able to use the item i added..

**Comment by MalibuSantez** [comment]
Did you find out how the item can be used in QBCore? Standalone version works great with the command, but as soon as I put it on QBCore I can't use the item.
