### ISSUE TITLE
Wrong Qbcore Export and its Solution\Fix !

### ISSUE THREAD

**Issue by Tamer173** [renzuzu/renzu_stancer#17]
The script does not initialize for QBCore due to wrong initialization for qb exports.

--    Script / File Path :   **renzu_stancer\framework\sv_wrapper.lua**   --
--    Line no  **9**   --

### Your Script Code Problem and Its Solution :

On line no 9 of sv_wrapper.lua File!

`QBCore = exports['qb-core']:GetSharedObject()`  <==  Change this to This  ==>    `QBCore = exports['qb-core']:GetCoreObject()`

This took me a while to find it but here if it helps!

And for anyone who is watching this please install fivem-mysql-async for your scripts to work properly. Thanks

**Comment by Tamer173** [comment]
> Did you ever get it to save to the database? Mine doesn't save it at all, also no errors. As soon as you take the car back out it doesn't load it

Try downloading the latest script he updated his script, it should work now.

**Comment by Tamer173** [comment]
> > > Did you ever get it to save to the database? Mine doesn't save it at all, also no errors. As soon as you take the car back out it doesn't load it
> > 
> > 
> > Try downloading the latest script he updated his script, it should work now.
> 
> I did get the latest version just now! But for some reason it doesn't save it to the database, even though I set the database to oxmysql and core to QB-CORE, still doesn't save it!

Brother did you read the Config file , it says if you use qbcore you need to add item in your qbcore/shared/items.lua file
The item is not given by developer you can make it its not that hard. 
After adding the item , give yourself item in game and check if its working or not

**Comment by Revline-RP** [comment]
> 

Hey, yes! Ofcourse I added it to the qb-core/shared/items.lua. I opened the issue in another post so you can see more about it bro! I am the developer for this server and have done it for many years. It just doesn't save it after I use it!
