### ISSUE TITLE
Item not register 

### ISSUE THREAD

**Issue by Loyzahk** [renzuzu/renzu_stancer#19]
Framework: QBCore
GameBuild: 2699 (latest)

Issue: The item not register , when i put /giveitem 1 stancerkit 1, the game print "The item doesn't exist"
![image](https://user-images.githubusercontent.com/95712901/185727583-b25b2ef7-342d-4118-bb8c-43f9bf61fa7d.png)

and i have this log in the console:
Log:
[    c-scripting-core] Creating script environments for renzu_stancer
[script:renzu_stancer] GAGO
[script:renzu_stancer] Error loading script server.lua in resource renzu_stancer: @renzu_stancer/framework/sv_wrapper.lua:7: attempt to index a nil value (global 'ESX')
[script:renzu_stancer] stack traceback:
[script:renzu_stancer] 	@renzu_stancer/framework/sv_wrapper.lua:7: in function 'Initialized'
[script:renzu_stancer] 	@renzu_stancer/server.lua:6: in main chunk
[    c-scripting-core] Failed to load script server.lua.
[ citizen-server-impl] Started resource renzu_stancer

**Comment by Tamer173** [comment]
> Framework: QBCore GameBuild: 2699 (latest)
> 
> Issue: The item not register , when i put /giveitem 1 stancerkit 1, the game print "The item doesn't exist" ![image](https://user-images.githubusercontent.com/95712901/185727583-b25b2ef7-342d-4118-bb8c-43f9bf61fa7d.png)
> 
> and i have this log in the console: Log: [ c-scripting-core] Creating script environments for renzu_stancer [script:renzu_stancer] GAGO [script:renzu_stancer] Error loading script server.lua in resource renzu_stancer: @renzu_stancer/framework/sv_wrapper.lua:7: attempt to index a nil value (global 'ESX') [script:renzu_stancer] stack traceback: [script:renzu_stancer] @renzu_stancer/framework/sv_wrapper.lua:7: in function 'Initialized' [script:renzu_stancer] @renzu_stancer/server.lua:6: in main chunk [ c-scripting-core] Failed to load script server.lua. [ citizen-server-impl] Started resource renzu_stancer

Bro go and Read Qbcore official Docs to know how to register an item , why keep opening the issue for these basic things, Anyway here is what you gotta do :
1. You should have a png file for the vstancer script that will show in your inventory. 
2. Paste the below code in your qb-core/shared/items.lua anywhere in the items.lua file and make sure it has comma ( , ) in the end.
` ["stancerkit"] = {["name"] = "stancerkit", ["label"] = "Stancer KIT", ["weight"] = 20000, ["type"] = "item", ["image"] = "laptop_prac.png", ["unique"] = true, ["useable"] = true, ["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Stancerkit for Vehicle Wheels"},`

**Comment by Loyzahk** [comment]
Thanks, but i tried it and still not working can you give me your discord to talk and fix?

**Comment by Tamer173** [comment]
> Thanks, but i tried it and still not working can you give me your discord to talk and fix?

Come Qasim#8732
