### ISSUE TITLE
Item doesn't work

### ISSUE THREAD

**Issue by Manta95** [renzuzu/renzu_stancer#2]
Hi Renzu,

Have a problem with your script under ESX : 

Item is in database, i have stancerkit in my inventory (esx_inventoryhud) and when I try to use it inside owned car (tested on spawned car too), the stancerkit isn't installed, nothing appear in database under renzu_stancer table. No error in server console or F8... Just the notification "No Stancer Kit Install"

![image](https://user-images.githubusercontent.com/64571534/139356197-92f8ce02-e4a5-48f5-a6cd-9b475d8f7356.png)

**Comment by Manta95** [comment]
I'm under onesync and item doesn't remove. Restarting whole server + deleting cache doesn't change anything.

Item in Db is removable : 

![image](https://user-images.githubusercontent.com/64571534/139497280-a9aa5b46-2d1a-461e-8d14-56f87d59847b.png)

**Comment by Manta95** [comment]
For what I have understand, I think the item doesn't remove cause it can't read something here (server.lua)

function AddStancerKit(veh)
  local veh = veh
  if veh == nil then veh = GetVehiclePedIsIn(GetPlayerPed(source),false) end
  plate = GetVehicleNumberPlateText(veh)
  if not stancer[plate] then
    stancer[plate] = {}
    local ent = Entity(veh).state
    if not ent.stancer then
      stancer[plate].stancer = {}
      stancer[plate].plate = plate
      stancer[plate].online = true
      ent.stancer = stancer[plate]
      SaveStancer({plate = plate, setting = {}})
    end
  end
end

**Comment by renzuzu** [comment]
```
if Config.Framework ~= 'Standalone' then
    for k,v in pairs(Config.items) do
      local stanceritem = string.lower(v)
      print("register item", v)
      RegisterUsableItem(stanceritem, function(source)
        local xPlayer = GetPlayerFromId(source)
        local veh = GetVehiclePedIsIn(GetPlayerPed(source),false)
        if stanceritem ~= nil and veh ~= 0 then
          xPlayer.removeInventoryItem(stanceritem, 1)
          AddStancerKit(veh)
        end
      end)
    end
  end
  
  ```
  
  simple condition to register item
  first must be non standalone
  2nd must be in vehicle
  3rd (possibly fxserver version (some fxversion have broken getvehicle native rpc via server)

**Comment by Manta95** [comment]
Ok then config.lua set to ESX, tested inside a car and with latest recommended artifacts (4394 under windows) ;)
