### ISSUE TITLE
Stance doesn't get saved into the database.

### ISSUE THREAD

**Issue by Revline-RP** [renzuzu/renzu_stancer#22]
Hello @renzuzu ,

I have just installed this script today. I am running QB-Core and oxmysql. So after I give myself the stancekit, then I use it. Then I use the command /stance and edit the stance of the car. After that I press on Save, but then when I /dv or park the vehicle. It goes back to default stance of the car. And when I try to do /stance again after I pulled it out of the garage it doesn't work. It says it's not installed on the car. But when I try to use the kit again, it gives the same error where I cant install it on the car. There are no errors in the Server Console, and also none in the Client Console. I tried looking in the player_vehicles table in the database but I can't seem to find anything to do with the stance. Where is this supposed to be saved? 

Thank you in advance!

**Comment by Tamer173** [comment]
You have to be in the vehicle and use the item, the ui will open, stance your vehicle and then save it , see if that works.

**Comment by Revline-RP** [comment]
> You have to be in the vehicle and use the item, the ui will open, stance your vehicle and then save it , see if that works.

I do that, only when I use the item nothing happens. I have to type /stance after using the item. Then when I save it, and pull it back it's not saved anymore on the car. See screenshots above.

**Comment by Tamer173** [comment]
Hmm its odd, well Developer can help you then, sorry to say he doesn't have a discord as far as i know 😑

**Comment by Revline-RP** [comment]
> Hmm its odd, well Developer can help you then, sorry to say he doesn't have a discord as far as i know 😑

I am the developer, if you want my discord, we can discuss it. My discord is Dobby#6434

**Comment by Revline-RP** [comment]
> Hmm its odd, well Developer can help you then, sorry to say he doesn't have a discord as far as i know 😑

Where did it get saved for you in the database btw? Because I don't see the table for it.

**Comment by Revline-RP** [comment]
Just pulled latest version, still the same unfortunately :(

**Comment by renzuzu** [comment]
Its possible in recent commits.

Since the stancer iterate 1 entity per plate, so duplicate plates may cause your problem.

Due to the other entities are taking the loop for stance setting.

But the no stancer install problem could be different issue,
The client will receive state bag events from handler to any entity with stancer state bags, even with duplicate plates.

The only problem i can see to that is client is not receiving state bags update

And The version of stancer now are using resource kvp for saving datas.

**Comment by Tamer173** [comment]
> Its possible in recent commits.
> 
> Since the stancer iterate 1 entity per plate, so duplicate plates may cause your problem.
> 
> Due to the other entities are taking the loop for stance setting.
> 
> But the no stancer install problem could be different issue, The client will receive state bag events from handler to any entity with stancer state bags, even with duplicate plates.
> 
> The only problem i can see to that is client is not receiving state bags update. Eg non network vehicle.
> 
> And The version of stancer now are using resource kvp for saving datas.

Can you make a check function in which the script check if you are the vehicle owner or not in order to use stance

**Comment by Revline-RP** [comment]
> Its possible in recent commits.
> 
> Since the stancer iterate 1 entity per plate, so duplicate plates may cause your problem.
> 
> Due to the other entities are taking the loop for stance setting.
> 
> But the no stancer install problem could be different issue, The client will receive state bag events from handler to any entity with stancer state bags, even with duplicate plates.
> 
> The only problem i can see to that is client is not receiving state bags update. Eg non network vehicle.
> 
> And The version of stancer now are using resource kvp for saving datas.

Allright, I will try it again. See if it now works with server side spawned cars too. Could be duplicate plates but there aren't any in the database. Might be civilian duplicate plate then driving somewhere.

**Comment by Tamer173** [comment]
> > Its possible in recent commits.
> > Since the stancer iterate 1 entity per plate, so duplicate plates may cause your problem.
> > Due to the other entities are taking the loop for stance setting.
> > But the no stancer install problem could be different issue, The client will receive state bag events from handler to any entity with stancer state bags, even with duplicate plates.
> > The only problem i can see to that is client is not receiving state bags update. Eg non network vehicle.
> > And The version of stancer now are using resource kvp for saving datas.
> 
> Allright, I will try it again. See if it now works with server side spawned cars too. Could be duplicate plates but there aren't any in the database. Might be civilian duplicate plate then driving somewhere.

Dm me on Discord Qasim#8732
If you want the stancer fully working.

**Comment by Revline-RP** [comment]
> > > Its possible in recent commits.
> > > Since the stancer iterate 1 entity per plate, so duplicate plates may cause your problem.
> > > Due to the other entities are taking the loop for stance setting.
> > > But the no stancer install problem could be different issue, The client will receive state bag events from handler to any entity with stancer state bags, even with duplicate plates.
> > > The only problem i can see to that is client is not receiving state bags update. Eg non network vehicle.
> > > And The version of stancer now are using resource kvp for saving datas.
> > 
> > 
> > Allright, I will try it again. See if it now works with server side spawned cars too. Could be duplicate plates but there aren't any in the database. Might be civilian duplicate plate then driving somewhere.
> 
> Dm me on Discord Qasim#8732 If you want the stancer fully working.

Added you discord name is Dobby

**Comment by bbeckann** [comment]
I have the same problem has anyone managed to fix it?
