### ISSUE TITLE
Deleting Stancer from vehicle

### ISSUE THREAD

**Issue by mastamadman** [renzuzu/renzu_stancer#24]
Currently with KVP, there is no way to remove a vehicle from stancer.

**Comment by renzuzu** [comment]
yea, because the not the real purpose of the script 
but its good idea to have uninstall system

here how you can do it
```
  local vehicle = GetVehiclePedIsIn(GetPlayerPed(source),false)
  local plate = GetVehicleNumberPlateText(vehicle)
  local ent = Entity(vehicle).state
  ent.stancer = nil
  local data = json.decode(GetResourceKvpString('stancer') or '[]') or {}
  data[plate] =nil
  SetResourceKvp('stancer',json.encode(data))
  
  ```
  this is server based.
  
  i would probably update them as soon as im done with current task.

**Comment by svicidepollo** [comment]
dude i been breaking my head trying to get a remover, i want to be able to remove the stance and get the item back if possible

**Comment by svicidepollo** [comment]
if we could have an item to remove the existing stancer that would be amazing
