### ISSUE TITLE
[FEATURE REQUEST] KVP or mysql

### ISSUE THREAD

**Issue by xrtw** [renzuzu/renzu_stancer#30]
please make option if you want to save and load from KVP or MySQL

**Comment by renzuzu** [comment]
your fucking rich bro, $200k for each plate? 👯 

sure, you have a legit use case. i wil implement

**Comment by renzuzu** [comment]
take note this is breaking change and will wipe everything from KVP.

**Comment by renzuzu** [comment]
im not sure if the old version OF mysql is the same format.

**Comment by renzuzu** [comment]
the new format saves only the wheelsetting table.

is it bad to wipe old datas? since stancer is easy to configure again by players :D
this could be the final format for this datas. and no more breaking change.

**Comment by renzuzu** [comment]
> https://i.gyazo.com/64849ea8b030e0366529317205c19858.png and this one is spamming when configuring wheels

re open a new issue with this
