### ISSUE TITLE
Wheels problem

### ISSUE THREAD

**Issue by Smailas01** [renzuzu/renzu_stancer#31]
Some times(almost every time) when you driving wheels go to orginal position like before edited with stancer.
And in F8 Console i saw this error when that happening. 
Im 'm using ESX legacy 1.8.5 with ox inventory.
![stancererror](https://user-images.githubusercontent.com/117887430/223948479-bf51e200-068f-4c93-8ed0-05f1c91183bd.png)
 
![image_2023-03-09_095153867](https://user-images.githubusercontent.com/117887430/223956064-de25567d-1745-4ef3-bf99-a837b84ffd57.png)

**Comment by renzuzu** [comment]
can you share some step by step to produce this?

**Comment by Smailas01** [comment]
Video:
https://medal.tv/games/gta-v/clips/YIUJGSqYwGdY2/d1337DmyTNpE?invite=cr-MSxXTEEsMjI5NTY1ODUs

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_stancer/commit/94b654e56b069698d2e018474dc74f8598480ab6

i pushed an update regarding wheel width and those errors

**Comment by Smailas01** [comment]
Still same like in video some times wheels go back to normal state and when you edit something car getting speed boost too
