### ISSUE TITLE
wheels

### ISSUE THREAD

**Issue by ahmoge** [renzuzu/renzu_stancer#32]
![image](https://user-images.githubusercontent.com/121356172/224350899-0bf28af0-f5a6-4658-a06d-efe325d82cdc.png)
after i saved the settings i made on the car and store it at the garage and pull it out again this error pops and the wheels will go back and forth to stock to the edited settings
framework : qbcore

**Comment by renzuzu** [comment]
oh shit its mistake from last commit

**Comment by ahmoge** [comment]
will update you sir :)

**Comment by ahmoge** [comment]
Fixed sir thank you very much
