### ISSUE TITLE
Wheel Turn Back To Normal

### ISSUE THREAD

**Issue by deputystrand** [renzuzu/renzu_stancer#33]
after editing the stance and save to garage and take back out the vehicle the edits that i make gone back to original and sometimes when i am driving the wheels will go in and out

**Comment by deputystrand** [comment]
![image](https://user-images.githubusercontent.com/123866484/224534636-540605ec-b011-4262-b0b1-b1acfd422a67.png)
Plus also i will get this error code some times

**Comment by deputystrand** [comment]
https://youtu.be/iB5YM3AzMC4

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_stancer/commit/ecdcd269e61bbfa454dfa46178067851da4fd76c

**Comment by deputystrand** [comment]
> [ecdcd26](https://github.com/renzuzu/renzu_stancer/commit/ecdcd269e61bbfa454dfa46178067851da4fd76c)

will try edit that line with the code you provide
