### ISSUE TITLE
getnetworkobject

### ISSUE THREAD

**Issue by ahmoge** [renzuzu/renzu_stancer#34]
![image](https://user-images.githubusercontent.com/121356172/225127989-fd321aad-50a3-4862-8909-672daec01b5b.png)
hello sir script is working fine but i always saw this "script:renzu_stancer: warning"  how can i remove it thanks.

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_stancer/commit/e0ad7e3862a9c0cab281db4bc27f467911790248

this should not appear anymore
