### ISSUE TITLE
No SQL File?

### ISSUE THREAD

**Issue by BrandsPickled** [renzuzu/renzu_stancer#35]
[script:renzu_stancer] SCRIPT ERROR: @renzu_stancer/server.lua:18: renzu_stancer was unable to execute a query!
[script:renzu_stancer] Table 'shadecityrp.renzu_stancer' doesn't exist
[script:renzu_stancer] SELECT * FROM renzu_stancer WHERE plate = ? ["20MKJ581"]

**Comment by BrandsPickled** [comment]
I  made one for you :)

```
CREATE TABLE `renzu_stancer` (
  `plate` varchar(128) NOT NULL,
  `setting` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;
```

**Comment by renzuzu** [comment]
its weird this auto install does not trigger to you?

![image](https://user-images.githubusercontent.com/82306584/227755287-4bbaace2-40e0-4f08-8cb3-937093ea1899.png)

**Comment by BrandsPickled** [comment]
Yeah, sadly it didn't, very weird mate. But I did that file and worked fine :)

**Comment by renzuzu** [comment]
this is fixed in latest version
