### ISSUE TITLE
Camber errors. When configuring stancer with menu entities error

### ISSUE THREAD

**Issue by xrtw** [renzuzu/renzu_stancer#36]
![64849ea8b030e0366529317205c19858](https://user-images.githubusercontent.com/55210961/229271963-ae63af1e-7914-4006-8bff-c38abee92d4d.png)

**Comment by renzuzu** [comment]
addon car probably does not support this. 
weird

**Comment by renzuzu** [comment]
can you take a long on the handling.meta 

if it includes `SubHandlingData`

```
<SubHandlingData>
        <Item type="CCarHandlingData">
          <fBackEndPopUpCarImpulseMult value="0.100000" />
          <fBackEndPopUpBuildingImpulseMult value="0.030000" />
          <fBackEndPopUpMaxDeltaSpeed value="0.600000" />
        </Item>
        <Item type="NULL" />
        <Item type="NULL" />
      </SubHandlingData>

**Comment by renzuzu** [comment]
you did not answer the question :D

**Comment by renzuzu** [comment]
now i know this params from handling is required, which is bad to use CCarhandling Setter
