### ISSUE TITLE
Issua when used item to car

### ISSUE THREAD

**Issue by Boosukka12** [renzuzu/renzu_stancer#43]
Hello got some issue when used item to car,i cant sell after that because esx_vehicleshop says plate is missmatching and i dont wana use renzu vehicleshop because that menudesign is 🤕

**Comment by renzuzu** [comment]
this resource does not change plates.

**Comment by Boosukka12** [comment]
ye i know that and i dindt ask that :) still after using item to car esx vehicleshop dont find plate belong to car :)

**Comment by Boosukka12** [comment]
no any ideas? at least this is your maked script and didnt know how to fix

**Comment by Boosukka12** [comment]
I fixed this shit too myself :)
