### ISSUE TITLE
possible to add wheelsize like vStancer? 

### ISSUE THREAD

**Issue by soniXx123** [renzuzu/renzu_stancer#5]

**Comment by renzuzu** [comment]
Yea, maybe ill add it but this will make the menu larger or un even size...

**Comment by soniXx123** [comment]
its only one more area and the UI can be a but smaller :) have a look on the vStancer menu.

**Comment by WrecksBG** [comment]
Wheels size and wheel width as well will be perfect

**Comment by Flowrider** [comment]
Wheels size and wheel width would be great to add that when you have time. Thanks.
